### ISSUE TITLE
swipe back on iOS and onTap to select

### ISSUE THREAD

**Issue by gbbest15** [hcbpassos/drag_select_grid_view#23] opened 2021-05-02 01:48 UTC
1. here i have two issue with the plugin, immediately i apply the plugin the swipe back to the previous page did not work on the page 
2. my onTap to select is not working until i long press any first item before the ontap to select will start working

**Comment by hcbpassos** [comment] 2021-05-02 02:06
> here i have two issue with the plugin, immediately i apply the plugin the swipe back to the previous page did not work on the page.

This happens because, internally, we're using `WillPopScope`. This widget prevents swipe back from working. To fix that, we must instead add an entry to the local history.

> my onTap to select is not working until i long press any first item before the ontap to select will start working

I'm not sure I understand what you mean. Would you mind further elaborating? Maybe an example can help.

**Comment by gbbest15** [comment] 2021-05-02 02:20
### This happens because, internally, we're using WillPopScope. This widget prevents swipe back from working. To fix that, we must instead add an entry to the local history.
can you explain how to fix this.... 

2.  so let me explain better,
if i first ontap any item in the view, the select is not working. so i long press any one item in the view then the select start working with the rest item with the ontap..

so let assume i have 5 itmes in the view, so i ontap item 1 to change the bgcolor to identify that is selected, the ontap will not work meaning it will not select, even if i select item 3 or 2 or 4, it will not select. until i long press any item from 1-5 then the bgcolor of the item i selected will change then the ontap for rest item will start working, 

that means after the first long press the ontop to select will start working

**Comment by hcbpassos** [comment] 2021-05-02 02:48
> can you explain how to fix this....

Don't worry about it, I'll sort it out soon ;)

> if i first ontap any item in the view, the select is not working. so i long press any one item in the view then the select start working with the rest item with the ontap..

That's the intended behavior. The reason is I must give the library user the opportunity to handle the regular tap. Imagine this library is used in a gallery app, just like Google Photos. When the user taps a photo, it must show the picture in another screen. If we were to start the selection without long-press, this would not be possible.

Your request is valid, though. In fact, there's a PR to add a flag so it's possible to start selection without long-press. Check https://github.com/hcbpassos/drag_select_grid_view/pull/18 out.

**Comment by gbbest15** [comment] 2021-05-02 02:58
thanks so much. please as soon you made changes let me know, so that i can give my boss date to fix it...

**Comment by hcbpassos** [comment] 2021-05-02 22:38
Fixed by 3a995c9122e4db5ce35276300f1908cdba72c4bb.

**Closed by hcbpassos** 2021-05-02 22:38 UTC
Labels: bug
